Dism /Add-Package /Image:"C:\WinPE_!archdir!\mount" /PackagePath:"C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Windows Preinstallation Environment\!archdir!\WinPE_OCs\zh-tw\WinPE-DismCmdlets_zh-tw.cab"
@REM Dism /Add-Package /Image:"C:\WinPE_!archdir!\mount" /PackagePath:"C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Windows Preinstallation Environment\!archdir!\WinPE_OCs\zh-tw\WinPE-LegacySetup_zh-tw.cab"
Dism /Add-Package /Image:"C:\WinPE_!archdir!\mount" /PackagePath:"C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Windows Preinstallation Environment\!archdir!\WinPE_OCs\zh-tw\WinPE-PmemCmdlets_zh-tw.cab"
Dism /Add-Package /Image:"C:\WinPE_!archdir!\mount" /PackagePath:"C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Windows Preinstallation Environment\!archdir!\WinPE_OCs\zh-tw\WinPE-SRT_zh-tw.cab"
@REM Dism /Add-Package /Image:"C:\WinPE_!archdir!\mount" /PackagePath:"C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Windows Preinstallation Environment\!archdir!\WinPE_OCs\zh-tw\WinPE-Setup-Server_zh-tw.cab"
Dism /Add-Package /Image:"C:\WinPE_!archdir!\mount" /PackagePath:"C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Windows Preinstallation Environment\!archdir!\WinPE_OCs\zh-tw\WinPE-WMI_zh-tw.cab"
Dism /Add-Package /Image:"C:\WinPE_!archdir!\mount" /PackagePath:"C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Windows Preinstallation Environment\!archdir!\WinPE_OCs\zh-tw\WinPE-Dot3Svc_zh-tw.cab"
Dism /Add-Package /Image:"C:\WinPE_!archdir!\mount" /PackagePath:"C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Windows Preinstallation Environment\!archdir!\WinPE_OCs\zh-tw\WinPE-MDAC_zh-tw.cab"
Dism /Add-Package /Image:"C:\WinPE_!archdir!\mount" /PackagePath:"C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Windows Preinstallation Environment\!archdir!\WinPE_OCs\zh-tw\WinPE-PowerShell_zh-tw.cab"
Dism /Add-Package /Image:"C:\WinPE_!archdir!\mount" /PackagePath:"C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Windows Preinstallation Environment\!archdir!\WinPE_OCs\zh-tw\WinPE-Scripting_zh-tw.cab"
@REM Dism /Add-Package /Image:"C:\WinPE_!archdir!\mount" /PackagePath:"C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Windows Preinstallation Environment\!archdir!\WinPE_OCs\zh-tw\WinPE-Setup_zh-tw.cab"
Dism /Add-Package /Image:"C:\WinPE_!archdir!\mount" /PackagePath:"C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Windows Preinstallation Environment\!archdir!\WinPE_OCs\zh-tw\WinPE-WinReCfg_zh-tw.cab"
Dism /Add-Package /Image:"C:\WinPE_!archdir!\mount" /PackagePath:"C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Windows Preinstallation Environment\!archdir!\WinPE_OCs\zh-tw\WinPE-EnhancedStorage_zh-tw.cab"
Dism /Add-Package /Image:"C:\WinPE_!archdir!\mount" /PackagePath:"C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Windows Preinstallation Environment\!archdir!\WinPE_OCs\zh-tw\WinPE-NetFx_zh-tw.cab"
Dism /Add-Package /Image:"C:\WinPE_!archdir!\mount" /PackagePath:"C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Windows Preinstallation Environment\!archdir!\WinPE_OCs\zh-tw\WinPE-RNDIS_zh-tw.cab"
Dism /Add-Package /Image:"C:\WinPE_!archdir!\mount" /PackagePath:"C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Windows Preinstallation Environment\!archdir!\WinPE_OCs\zh-tw\WinPE-SecureStartup_zh-tw.cab"
Dism /Add-Package /Image:"C:\WinPE_!archdir!\mount" /PackagePath:"C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Windows Preinstallation Environment\!archdir!\WinPE_OCs\zh-tw\WinPE-StorageWMI_zh-tw.cab"
Dism /Add-Package /Image:"C:\WinPE_!archdir!\mount" /PackagePath:"C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Windows Preinstallation Environment\!archdir!\WinPE_OCs\zh-tw\lp.cab"
Dism /Add-Package /Image:"C:\WinPE_!archdir!\mount" /PackagePath:"C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Windows Preinstallation Environment\!archdir!\WinPE_OCs\zh-tw\WinPE-HTA_zh-tw.cab"
Dism /Add-Package /Image:"C:\WinPE_!archdir!\mount" /PackagePath:"C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Windows Preinstallation Environment\!archdir!\WinPE_OCs\zh-tw\WinPE-PPPoE_zh-tw.cab"
Dism /Add-Package /Image:"C:\WinPE_!archdir!\mount" /PackagePath:"C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Windows Preinstallation Environment\!archdir!\WinPE_OCs\zh-tw\WinPE-Rejuv_zh-tw.cab"
@REM Dism /Add-Package /Image:"C:\WinPE_!archdir!\mount" /PackagePath:"C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Windows Preinstallation Environment\!archdir!\WinPE_OCs\zh-tw\WinPE-Setup-Client_zh-tw.cab"
Dism /Add-Package /Image:"C:\WinPE_!archdir!\mount" /PackagePath:"C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Windows Preinstallation Environment\!archdir!\WinPE_OCs\zh-tw\WinPE-WDS-Tools_zh-tw.cab"


Dism /Set-AllIntl:zh-TW /Image:"C:\WinPE_!archdir!\mount"

