Dism /Add-Package /Image:"C:\WinPE_!archdir!\mount" /PackagePath:"C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Windows Preinstallation Environment\!archdir!\WinPE_OCs\zh-cn\WinPE-DismCmdlets_zh-cn.cab"
@REM Dism /Add-Package /Image:"C:\WinPE_!archdir!\mount" /PackagePath:"C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Windows Preinstallation Environment\!archdir!\WinPE_OCs\zh-cn\WinPE-LegacySetup_zh-cn.cab"
Dism /Add-Package /Image:"C:\WinPE_!archdir!\mount" /PackagePath:"C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Windows Preinstallation Environment\!archdir!\WinPE_OCs\zh-cn\WinPE-PmemCmdlets_zh-cn.cab"
Dism /Add-Package /Image:"C:\WinPE_!archdir!\mount" /PackagePath:"C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Windows Preinstallation Environment\!archdir!\WinPE_OCs\zh-cn\WinPE-SRT_zh-cn.cab"
@REM Dism /Add-Package /Image:"C:\WinPE_!archdir!\mount" /PackagePath:"C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Windows Preinstallation Environment\!archdir!\WinPE_OCs\zh-cn\WinPE-Setup-Server_zh-cn.cab"
Dism /Add-Package /Image:"C:\WinPE_!archdir!\mount" /PackagePath:"C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Windows Preinstallation Environment\!archdir!\WinPE_OCs\zh-cn\WinPE-WMI_zh-cn.cab"
Dism /Add-Package /Image:"C:\WinPE_!archdir!\mount" /PackagePath:"C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Windows Preinstallation Environment\!archdir!\WinPE_OCs\zh-cn\WinPE-Dot3Svc_zh-cn.cab"
Dism /Add-Package /Image:"C:\WinPE_!archdir!\mount" /PackagePath:"C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Windows Preinstallation Environment\!archdir!\WinPE_OCs\zh-cn\WinPE-MDAC_zh-cn.cab"
Dism /Add-Package /Image:"C:\WinPE_!archdir!\mount" /PackagePath:"C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Windows Preinstallation Environment\!archdir!\WinPE_OCs\zh-cn\WinPE-PowerShell_zh-cn.cab"
Dism /Add-Package /Image:"C:\WinPE_!archdir!\mount" /PackagePath:"C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Windows Preinstallation Environment\!archdir!\WinPE_OCs\zh-cn\WinPE-Scripting_zh-cn.cab"
@REM Dism /Add-Package /Image:"C:\WinPE_!archdir!\mount" /PackagePath:"C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Windows Preinstallation Environment\!archdir!\WinPE_OCs\zh-cn\WinPE-Setup_zh-cn.cab"
Dism /Add-Package /Image:"C:\WinPE_!archdir!\mount" /PackagePath:"C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Windows Preinstallation Environment\!archdir!\WinPE_OCs\zh-cn\WinPE-WinReCfg_zh-cn.cab"
Dism /Add-Package /Image:"C:\WinPE_!archdir!\mount" /PackagePath:"C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Windows Preinstallation Environment\!archdir!\WinPE_OCs\zh-cn\WinPE-EnhancedStorage_zh-cn.cab"
Dism /Add-Package /Image:"C:\WinPE_!archdir!\mount" /PackagePath:"C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Windows Preinstallation Environment\!archdir!\WinPE_OCs\zh-cn\WinPE-NetFx_zh-cn.cab"
Dism /Add-Package /Image:"C:\WinPE_!archdir!\mount" /PackagePath:"C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Windows Preinstallation Environment\!archdir!\WinPE_OCs\zh-cn\WinPE-RNDIS_zh-cn.cab"
Dism /Add-Package /Image:"C:\WinPE_!archdir!\mount" /PackagePath:"C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Windows Preinstallation Environment\!archdir!\WinPE_OCs\zh-cn\WinPE-SecureStartup_zh-cn.cab"
Dism /Add-Package /Image:"C:\WinPE_!archdir!\mount" /PackagePath:"C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Windows Preinstallation Environment\!archdir!\WinPE_OCs\zh-cn\WinPE-StorageWMI_zh-cn.cab"
Dism /Add-Package /Image:"C:\WinPE_!archdir!\mount" /PackagePath:"C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Windows Preinstallation Environment\!archdir!\WinPE_OCs\zh-cn\lp.cab"
Dism /Add-Package /Image:"C:\WinPE_!archdir!\mount" /PackagePath:"C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Windows Preinstallation Environment\!archdir!\WinPE_OCs\zh-cn\WinPE-HTA_zh-cn.cab"
Dism /Add-Package /Image:"C:\WinPE_!archdir!\mount" /PackagePath:"C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Windows Preinstallation Environment\!archdir!\WinPE_OCs\zh-cn\WinPE-PPPoE_zh-cn.cab"
Dism /Add-Package /Image:"C:\WinPE_!archdir!\mount" /PackagePath:"C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Windows Preinstallation Environment\!archdir!\WinPE_OCs\zh-cn\WinPE-Rejuv_zh-cn.cab"
@REM Dism /Add-Package /Image:"C:\WinPE_!archdir!\mount" /PackagePath:"C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Windows Preinstallation Environment\!archdir!\WinPE_OCs\zh-cn\WinPE-Setup-Client_zh-cn.cab"
Dism /Add-Package /Image:"C:\WinPE_!archdir!\mount" /PackagePath:"C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Windows Preinstallation Environment\!archdir!\WinPE_OCs\zh-cn\WinPE-WDS-Tools_zh-cn.cab"


Dism /Set-AllIntl:zh-CN /Image:"C:\WinPE_!archdir!\mount"

